import { getClaudeConfigDir, writeFile, fileExists } from "./tauriBridge";
import { readClaudeCodeSettings, writeClaudeCodeSettings } from "./cliSyncService";

/** Generate PowerShell statusline fetch script content */
function generateFetchScript(sessionKey: string, orgId: string): string {
  return `# fetch-claude-usage.ps1
# Generated by Claude Usage Tracker for Windows
# This script fetches usage data and caches it for the statusline

$ErrorActionPreference = "SilentlyContinue"

$sessionKey = "${sessionKey}"
$orgId = "${orgId}"
$cacheDir = "$env:USERPROFILE\\.claude"
$cacheFile = "$cacheDir\\usage-cache.json"

# Ensure cache dir exists
if (-not (Test-Path $cacheDir)) {
    New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
}

try {
    $headers = @{
        "Cookie" = "sessionKey=$sessionKey"
        "Accept" = "application/json"
    }

    $response = Invoke-RestMethod -Uri "https://claude.ai/api/organizations/$orgId/usage" -Headers $headers -Method Get -TimeoutSec 10

    $usage = @{
        session_pct = if ($response.five_hour.utilization_pct) { $response.five_hour.utilization_pct } else { $response.five_hour.utilization }
        session_resets = $response.five_hour.resets_at
        weekly_pct = if ($response.seven_day.utilization_pct) { $response.seven_day.utilization_pct } else { $response.seven_day.utilization }
        weekly_resets = $response.seven_day.resets_at
        opus_pct = if ($response.seven_day_opus.utilization_pct) { $response.seven_day_opus.utilization_pct } else { $response.seven_day_opus.utilization }
        fetched_at = (Get-Date -Format "o")
    }

    $usage | ConvertTo-Json -Depth 3 | Set-Content -Path $cacheFile -Encoding UTF8
    Write-Output "OK"
} catch {
    Write-Output "ERROR: $_"
    exit 1
}
`;
}

/** Generate PowerShell statusline command script */
function generateStatuslineScript(): string {
  return `# statusline-command.ps1
# Generated by Claude Usage Tracker for Windows
# Reads cached usage data and outputs a formatted statusline

$cacheFile = "$env:USERPROFILE\\.claude\\usage-cache.json"

if (-not (Test-Path $cacheFile)) {
    Write-Output "No data"
    exit 0
}

try {
    $data = Get-Content -Path $cacheFile -Raw | ConvertFrom-Json
    $fetchedAt = [DateTime]::Parse($data.fetched_at)
    $age = (Get-Date) - $fetchedAt

    # Stale if older than 10 minutes
    if ($age.TotalMinutes -gt 10) {
        Write-Output "Stale"
        exit 0
    }

    $sessionPct = [math]::Round($data.session_pct, 0)
    $weeklyPct = [math]::Round($data.weekly_pct, 0)

    # Reset time
    $resetTime = ""
    if ($data.session_resets) {
        $resets = [DateTime]::Parse($data.session_resets)
        $diff = $resets - (Get-Date)
        if ($diff.TotalMinutes -gt 0) {
            $h = [math]::Floor($diff.TotalHours)
            $m = [math]::Floor($diff.TotalMinutes % 60)
            $resetTime = " R:$\{h}h$\{m}m"
        }
    }

    Write-Output "S:$\{sessionPct}% W:$\{weeklyPct}%$resetTime"
} catch {
    Write-Output "Error"
    exit 1
}
`;
}

/** Install statusline scripts to %USERPROFILE%\.claude\ */
export async function installStatuslineScripts(
  sessionKey: string,
  orgId: string,
): Promise<void> {
  const configDir = await getClaudeConfigDir();

  const fetchScript = generateFetchScript(sessionKey, orgId);
  const statuslineScript = generateStatuslineScript();

  await writeFile(`${configDir}\\fetch-claude-usage.ps1`, fetchScript);
  await writeFile(`${configDir}\\statusline-command.ps1`, statuslineScript);
}

/** Update Claude Code settings.json to use the statusline */
export async function configureClaudeCodeStatusline(enabled: boolean): Promise<void> {
  const configDir = await getClaudeConfigDir();
  const settings = (await readClaudeCodeSettings()) ?? {};

  if (enabled) {
    const scriptPath = `${configDir}\\statusline-command.ps1`.replace(/\\/g, "\\\\");
    settings["statusline"] = `powershell -ExecutionPolicy Bypass -File "${scriptPath}"`;
  } else {
    delete settings["statusline"];
  }

  await writeClaudeCodeSettings(settings);
}

/** Check if statusline scripts are installed */
export async function isStatuslineInstalled(): Promise<boolean> {
  const configDir = await getClaudeConfigDir();
  return await fileExists(`${configDir}\\statusline-command.ps1`);
}
